### ISSUE TITLE
Cannot list operations in swagger interface

### ISSUE THREAD

**Issue by claudyus** [ninuxorg/nodeshot#255]
After the update of django-rest-framework the swagger interface can not retieve information about API. On the frontend this error is reported:
```
Unable to read api 'v1' from path http://nodeshot.dok********/api/v1/docs/api-docs/api/v1 (server returned INTERNAL SERVER ERROR)
```

While in error log I can see:
```
Internal Server Error: /api/v1/docs/api-docs/api/v1
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 456, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 453, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rest_framework_swagger/views.py", line 151, in get
    'apis': generator.generate(apis),
  File "/usr/local/lib/python2.7/site-packages/rest_framework_swagger/docgenerator.py", line 41, in generate
    'operations': self.get_operations(api, apis),
  File "/usr/local/lib/python2.7/site-packages/rest_framework_swagger/docgenerator.py", line 76, in get_operations
    serializer = self._get_method_serializer(method_introspector)
  File "/usr/local/lib/python2.7/site-packages/rest_framework_swagger/docgenerator.py", line 172, in _get_method_serializer
    serializer = method_inspector.get_response_serializer_class()
  File "/usr/local/lib/python2.7/site-packages/rest_framework_swagger/introspectors.py", line 234, in get_response_serializer_class
    serializer = self.get_serializer_class()
  File "/usr/local/lib/python2.7/site-packages/rest_framework_swagger/introspectors.py", line 227, in get_serializer_class
    serializer = self.ask_for_serializer_class()
  File "/usr/local/lib/python2.7/site-packages/rest_framework_swagger/introspectors.py", line 210, in ask_for_serializer_class
    return view.get_serializer_class()
  File "/usr/local/lib/python2.7/site-packages/rest_framework/generics.py", line 124, in get_serializer_class
    % self.__class__.__name__
AssertionError: 'ContactNode' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
```

Bug based on a dockerized version of nodeshot at revision 1b342f1787

**Comment by nemesisdesign** [comment]
For some reason in ``ContactNode`` I commented out the ``serializer_class`` attribute commented:
https://github.com/ninuxorg/nodeshot/blob/master/nodeshot/community/mailing/views.py#L27

@claudyus @cvalenti Could you try to uncomment and try to see if it fixes the issue?

**Comment by claudyus** [comment]
I just uncomment it but #somethinghappened

```
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./nodeshot/ui/default/views.py", line 40, in index
    layers = LayerDetailSerializer(layers, many=True, context=serializer_context).data
  File "/usr/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 622, in data
    ret = super(ListSerializer, self).data
  File "/usr/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 217, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 572, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/usr/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 439, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/relations.py", line 264, in to_representation
    return self.get_url(value, self.view_name, request, format)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/relations.py", line 204, in get_url
    return self.reverse(view_name, kwargs=kwargs, request=request, format=format)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/reverse.py", line 26, in reverse
    return _reverse(viewname, args, kwargs, request, format, **extra)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/reverse.py", line 37, in _reverse
    url = django_reverse(viewname, args=args, kwargs=kwargs, **extra)
  File "/usr/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/usr/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 433, in _reverse_with_prefix
    self._populate()
  File "/usr/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 308, in _populate
    for name in pattern.reverse_dict:
  File "/usr/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 338, in reverse_dict
    self._populate()
  File "/usr/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 308, in _populate
    for name in pattern.reverse_dict:
  File "/usr/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 338, in reverse_dict
    self._populate()
  File "/usr/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 308, in _populate
    for name in pattern.reverse_dict:
  File "/usr/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 338, in reverse_dict
    self._populate()
  File "/usr/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 326, in _populate
    lookups.appendlist(pattern.callback, (bits, p_pattern, pattern.default_args))
  File "/usr/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 247, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/local/lib/python2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 106, in get_callable
    mod = import_module(mod_name)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./nodeshot/community/mailing/views.py", line 17, in <module>
    class ContactNode(generics.GenericAPIView):
  File "./nodeshot/community/mailing/views.py", line 27, in ContactNode
    serializer_class = InwardSerializer
NameError: name 'InwardSerializer' is not defined
```

**Comment by nemesisdesign** [comment]
@claudyus oh I see, the API works anyway because the `post` method of `nodeshot.community.mailing.views.ContactNode` is overwritten, but DRF-swagger still needs a Serializer in order to generate the docs.

See here, there's a deleted `serializers.py`:
https://github.com/ninuxorg/nodeshot/commit/3263eb6eb26a92e5fc54be77d40b3c0b4ff4835f

Could you try putting it back (renaming it to `InwardSerializer`) and import it from `views.py`?
